### ISSUE TITLE
Could you please show the support list for distributed Deep Learning networks?

### ISSUE THREAD

**Issue by databig** [BIDData/BIDMach#25]
Could you please show the support list for distributed Deep Learning networks?
How to do the Data Partition/Model Partition in BIDMACH

**Comment by databig** [comment]
Any Comment? @jcanny

**Comment by jcanny** [comment]
Deep learning support is a work-in-progress. Its in a branch called "caffe". 

See the docs on datasources for preparing a set of files for very large datasets. We havent done much on distributed ML, simply because there arent many datasets around that merit it. But it is a current topic of work, especially for distributed deep leanring. The code for "Kylix" distributed sparse allreduce is in the src/main/java/edu/berkeley/bid subdirectory. Allreduce is general enough to cover both distributed data and distributed models.

**Comment by jcanny** [comment]
We have several projects active now. One is BIDMach_on_Spark which will migrate and extend the Kylix code that's currently in BIDMat to run on top of Spark.
