### ISSUE TITLE
Integration with Spark?

### ISSUE THREAD

**Issue by databig** [BIDData/BIDMach#26]
I heard that u have integrated with Caffee, however, Caffee supports GPU as well.
Could you please list the reasons why need BIDMach for Caffee?
What's more, Support the Spark Integration? 
How to integrate with Spark?

**Comment by databig** [comment]
Any Comment? @jcanny

**Comment by jcanny** [comment]
For caffe we have several goals: 
* allow interaction with caffe through an interactive interface - caffe has python, so this isnt unique, but scala has various advantages. 
* allow running caffe from Java (well from JVM) to allow it to run distributed under various frameworks such as yarn, storm etc. We have developed butterfly mixing and Kylix to support fast allreduces on networks and deep learning is a natural target. 
* improve portability of caffe. By building on the JVM with minimal dependencies and building the binaries as we do with BIDMach, we allow caffe to be used without complex installs. The goal is to produce unzip-only distributions for Mac, Windows and Linux. 
* allow integration of caffe with other BIDMach components, e.g. mixing and Kylix but also other optimizers, regularizers, etc., pipe caffe output to other learners like random forests etc. 

We are working a bit with Spark folks but integration is quite challenging. BIDMach has a minibatch design and expects continuous allreduce updates when run on a network. Spark is a mapreduce system designed to support batch algorithms. We;ll see where that goes, but its not an ideal mix.We dont really need Spark's in memory data cache, since most of our algorithms run very well directly from disk and can run at much larger scale as a consequence. I do think it would be very useful for Spark to support mini-batch learners which requires a "next" block data method and a fast allreduce, but that doesnt seem to be a priority for them. 

We are also working on other kinds of integration with the Hadoop ecosystem to run BIDMach distributed. All we need for BIDMach are HDFS, a task allocator and an allreduce which we implement ourselves. So the natural frameworks to build on are Yarn or perhaps Mesos or Storm.

**Comment by databig** [comment]
Dear Prof. @jcanny  Thanks to your reply.
Actually, Why i come up with the question because we want to achieve extremely  Data&Model parallelism in the Large DBN Training.
That's the reason we should  utilize the advantages of Spark in the Distributed Computing.
Could you please show me more details in the BIDMach's design in the Distributed Deep Learning?
How to design the Parameter Server? How to update the weight(model)? ......
I found that ur group have a paper about BIDMach, or May I read this paper as well?
Tks.

**Comment by jcanny** [comment]
Here's the project page:
http://bid2.berkeley.edu/bid-data-project/publications/
There is a paper there on "Kylix" which is a near-optimal allreduce (a synchronous version of parameter sever). We havent spent a lot of time integrating kylix with BIDMach because we're unsure of the demand. A lot of the cluster workloads right now could run on single machines, and we're focused on writing near-optimal implementations of the popular ML algorithms. In almost all cases, those implementations are the fastest there is (including cluster versions). By adding a fast network allreduce we will be able to scale up all of the existing algorithms, if there is a need for it. 

How big are your DBNs?

**Comment by databig** [comment]
@jcanny  Could you please kindly put the paper:"BIDMach: A Very Fast and Scalable ML Toolkit for Big Data" to Arxiv? 
Another question: Does BIDMat can compile successfully in CUDA 6.5? 
My GPU server has installed 
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2014 NVIDIA Corporation
Built on Thu_Jul_17_21:41:27_CDT_2014
Cuda compilation tools, release 6.5, V6.5.12
I downloaded the update BIDMat code for GIT
sbt package
[info] Set current project to BIDMat (in build file:/home/aaa/biddata/BIDMat/)
[warn] Credentials file /home/aaa/.ivy2/.credentials does not exist
[info] Compiling 34 Scala sources and 14 Java sources to /home/aaa/biddata/BIDMat/target/scala-2.11/classes...
[error] /home/aaa/biddata/BIDMat/src/main/scala/BIDMat/SciFunctions.scala:7: not found: object jcuda
[error] import jcuda._;

Could you please help me ? @jcanny

**Comment by databig** [comment]
Could you please help me ? @jcanny

**Comment by jcanny** [comment]
Take a look at the documentation, especially the installation instructions:
https://github.com/BIDData/BIDMach/wiki/Installing-and-Running
that should tell you what you need to know...
