### ISSUE TITLE
Opening iScala via bidmach notebook leads to kernel crash

### ISSUE THREAD

**Issue by coryschillaci** [BIDData/BIDMach#28]
I downloaded BIDMach 1.0.0 for 64-bit Mac OSX

I'm using OSX Yosemite 10.10.2 with iPython 2.4.1

After expanding, I run

`./bidmach notebook`

Shortly after opening any of the iScala tutorial notebooks I get an error message: 
>The kernel appears to have died. It will restart automatically." 

and then eventually 

>"The kernel has died, and the automatic restart has failed. It is possible the kernel cannot be restarted. If you are not able to restart the kernel, you will still be able to save the notebook, but running code will no longer work until the notebook is reopened."

The command line output is 

>2015-02-20 14:01:07.815 [NotebookApp] Using existing profile dir: u'/Users/coryschillaci/.ipython/profile_scala'
2015-02-20 14:01:07.823 [NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
2015-02-20 14:01:07.847 [NotebookApp] Serving notebooks from local directory: /Users/coryschillaci/Desktop/Stress Project/BIDMach_1.0.0-osx-x86_64
2015-02-20 14:01:07.847 [NotebookApp] 0 active kernels 
2015-02-20 14:01:07.848 [NotebookApp] The IPython Notebook is running at: http://localhost:8888/
2015-02-20 14:01:07.848 [NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
2015-02-20 14:01:15.166 [NotebookApp] Kernel started: ef8b0c9b-34f5-4397-b931-67d0c5684209
Error: Could not find or load main class org.refptr.iscala.IScala
2015-02-20 14:01:18.169 [NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel ef8b0c9b-34f5-4397-b931-67d0c5684209 restarted
Error: Could not find or load main class org.refptr.iscala.IScala
2015-02-20 14:01:21.176 [NotebookApp] KernelRestarter: restarting kernel (2/5)
WARNING:root:kernel ef8b0c9b-34f5-4397-b931-67d0c5684209 restarted
Error: Could not find or load main class org.refptr.iscala.IScala
2015-02-20 14:01:24.185 [NotebookApp] KernelRestarter: restarting kernel (3/5)
WARNING:root:kernel ef8b0c9b-34f5-4397-b931-67d0c5684209 restarted
Error: Could not find or load main class org.refptr.iscala.IScala
2015-02-20 14:01:27.194 [NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel ef8b0c9b-34f5-4397-b931-67d0c5684209 restarted
Error: Could not find or load main class org.refptr.iscala.IScala
2015-02-20 14:01:30.207 [NotebookApp] WARNING | KernelRestarter: restart failed
2015-02-20 14:01:30.207 [NotebookApp] WARNING | Kernel ef8b0c9b-34f5-4397-b931-67d0c5684209 died, removing from map.
ERROR:root:kernel ef8b0c9b-34f5-4397-b931-67d0c5684209 restarted failed!

**Comment by jcanny** [comment]
There was a path problem which caused it to miss loading native libs on Mac OS (although I didnt see kernel crashes). Its fixed in the master branch. Try doing a git pull to see if it works. 

Your problem seems to be in the java classpath however. If the above doesnt work, can you edit the bidmach command (BIDMach root directory) and change:
   ipython notebook --profile scala --KernelManager.kernel_cmd="$KERNEL_CMD"
to
echo   ipython notebook --profile scala --KernelManager.kernel_cmd="$KERNEL_CMD"
and send me the output? 
I'm looking to see whether the script is correctly finding the BIDMach root directory. If it cant, the classpath will be wrong which is the most common problem here.

**Comment by coryschillaci** [comment]
I still get the same behavior. The output is 
>ipython notebook --profile scala --KernelManager.kernel_cmd=["java", "-cp", ":./lib/IScala.jar:./BIDMach.jar:./lib/BIDMat.jar:./lib/ptplot.jar:./lib/ptplotapplication.jar:./lib/jhdf5.jar:./lib/commons-math3-3.2.jar:./lib/lz4-1.1.2.jar:./lib/jcuda-0.6.5.jar:./lib/jcublas-0.6.5.jar:./lib/jcufft-0.6.5.jar:./lib/jcurand-0.6.5.jar:./lib/jcusparse-0.6.5.jar:/lib/tools.jar", "-Djava.library.path=", "-Xmx14G", "-Xms128M", "-Dfile.encoding=UTF-8", "org.refptr.iscala.IScala", "--profile", "{connection_file}", "--parent"]

**Comment by jcanny** [comment]
OK, the script is calculating the BIDMach root directory as "." instead of the absolute path. When run in Ipython, its in a different directory so it fails. 

Sigh, the script is trying hard *not* to get "." as the current directory. I'll try to fix it, but in the mean time you should find that if you start the script anywhere *except* the BIDMach root directory, it will work.

**Comment by coryschillaci** [comment]
You're right, it does work if I call the script from elsewhere. Thanks for your help.

**Comment by jcanny** [comment]
The script is modified now so it will work from anywhere. You can grab from master branch or the zip files have been updated.
