### ISSUE TITLE
getdata.sh either too slow or non-functional on parsing docword.nips

### ISSUE THREAD

**Issue by helgammal** [BIDData/BIDMach#30]
This error originates from the script getuci.sh. 

I verified that the URLs used in the wget requests were valid. The problem seems to be when running the tparse script on this [line] (https://github.com/BIDData/BIDMach/blob/master/scripts/getuci.sh#L36). 

It might be a good idea to have tparse output some error messages for us to know what's going on.

**Comment by jcanny** [comment]
Its caused by a missing format file (uci_wfmt.txt). It was fixed a few days ago and pushed to master branch and to the prebuilt bundles. 

Agreed it would be good to have some error messages for missing files. If you look at the code (tparse.ccp), it tests for both the "bad bit" and EOF bits when it opens a file, but apparently missing files generate neither of these. Its a bit of a quandry.

**Comment by jcanny** [comment]
Sorry, it didnt get pushed to the Mac tar file. Its there now. Also edited the source code so it should throw an exception if the format file is missing.
