### ISSUE TITLE
Issues compiling with latest version

### ISSUE THREAD

**Issue by coryschillaci** [BIDData/BIDMach#42]
When I pulled the latest version and then tried to compile, sbt gives the following errors:
```
~/BIDMach$ sbt package
[info] Set current project to BIDMach (in build file:/home/schillaci/BIDMach/)
[warn] Credentials file /home/schillaci/.ivy2/.credentials does not exist
[info] Compiling 16 Scala sources and 2 Java sources to /home/schillaci/BIDMach/target/scala-2.11/classes...
[error] /home/schillaci/BIDMach/src/main/scala/BIDMach/models/DNN.scala:568: value blockGemm is not a member of BIDMat.Mat
[error]       inputs(0).data.blockGemm(1, 0, nr, nc, reps, 
[error]                      ^
[error] /home/schillaci/BIDMach/src/main/scala/BIDMach/models/DNN.scala:580: value blockGemm is not a member of BIDMat.Mat
[error]       inputs(1).data.blockGemm(0, 1, nrows, nc, reps, 
[error]                      ^
[error] /home/schillaci/BIDMach/src/main/scala/BIDMach/models/DNN.scala:585: value blockGemm is not a member of BIDMat.Mat
[error]       inputs(0).data.blockGemm(0, 0, nrows, nr, reps, 
[error]                      ^
[error] three errors found
[error] (compile:compile) Compilation failed
[error] Total time: 12 s, completed Apr 9, 2015 12:20:39 PM
```
I tried copying the lib files from the latest executable bundles, but it didn't help.  Any idea what's up?

**Comment by DanielTakeshi** [comment]
Are you just doing ./sbt package? A recent update made it so that we don't have to copy over the BIDMach.jar files over.

**Comment by coryschillaci** [comment]
Yes, running `./sbt package` gives the error. I updated the issue above to include the input and the full output in case that helps.

**Comment by DanielTakeshi** [comment]
I am pretty sure I ran into this same exact error a few days ago because the blockGemm method sounds familiar to me, and I'm not working on DNN.scala. I think one of these combinations helped:

(1) Using ./sbt package without copying over any BIDMach.jar files to the current directory (which I mentioned above, unfortunately this doesn't seem to be your issue).
(2) Updating my BIDMat directory from master, compiling it there (also being sure to do just ./sbt package without copying things), and copying over the BIDMat.jar file over to the lib folder in BIDMach. But it seems like you already did that when you mention you "copied the lib files from the latest executable bundles", unless by executable bundles you're referring to an out of date BIDMat version (e.g., version 1.0.1) as opposed to the master branch for BIDMat?

**Comment by coryschillaci** [comment]
I think the issue must be in DNN.scala, if I revert just that file to an old enough commit (d1e502e77be069797200771f578825698afad34a worked) everything compiles just fine. I do have the most up to date BIDMat.jar as well, so that shouldn't be the problem.

**Comment by jcanny** [comment]
Its a new function in BIDMat. If you follow Daniel's suggestion and update BIDMat and then copy the jar across, you'll be fine. 

-John

**Comment by coryschillaci** [comment]
I was doing that, but it turns out that the lib files copied from the 1.0.0 build also contain a file `bidmat_2.11-0.9.8.jar` which was apparently being used rather than `BIDMat.jar` for the BIDMat definitions by sbt. I removed this and it works now.

**Comment by DanielTakeshi** [comment]
Closing because it appears to be resolved.
