### ISSUE TITLE
How do I run PageRank and Matrix Factorization

### ISSUE THREAD

**Issue by cuihenggang** [BIDData/BIDMach#49]
Hi,

I'm new here. The benchmarks look amazing. I'm interested in trying PageRank and Matrix Factorization on GPU. Do you have any documentations about running these two applications? Could you also point to me the CUDA code of these two applications?

Thanks,
Cui

**Comment by jcanny** [comment]
Matrxi factorization is the "SFA" learner. It gets run as one of the standard benchmarks in the workout.ssc script. 

Pagerank uses a distributed protocol called Kylix which is actually part of the BIDMat library. We're integrating it with Spark now, to make it easier to run and so that you can pull data directly from HDFS.
