### ISSUE TITLE
Start a Gitter Chat Room for BIDMach / BIDMat

### ISSUE THREAD

**Issue by danielchalef** [BIDData/BIDMach#55]
Please start a https://gitter.im/ Chat Room for BIDMach / BIDMat. Documentation for the projects is sparse, and adoption will remain limited unless the user community has an opportunity to interact with the project authors and other community members.

This approach is used very successfully by a large number of github-hosted projects.

**Comment by DanielTakeshi** [comment]
Thanks for this suggestion. I will check out gitter. I never heard of it before, and if it looks like it might be helpful I can bring this up with John later.

By the way, do you have a specific area or high-level suggestion for our documentation that I can clarify?

**Comment by danielchalef** [comment]
Thanks, Daniel. I'm having difficulty using Word2Vec load / save Google vector files, and would love to see some sample code.

**Comment by jcanny** [comment]
It should be there now. Can you find it and post to it?

**Comment by danielchalef** [comment]
Hi, thanks for creating the room. I can't seem to find either a BIDMach or BIDMat room in the search. Could you perhaps add the Gitter link or badge to the README of the project, or the wiki?

Thanks!

**Comment by DanielTakeshi** [comment]
The Gitter room is called BIDData. I just joined via an email invitation, but I assume there's a way for you to search it? Let us know if you still cannot find it.

With regards to Word2Vec, there are a couple of examples from the [Berkeley Institute for Data Science (BIDS) destress project repository](https://github.com/berkeley-dsc/destress) somewhere, but it's hard to learn from that so I agree, some form of documentation will be helpful. I've been meaning to learn how to use that code for a while so maybe this will motivate me to write something. I'll keep this issue here open for future reference.

**Comment by DanielTakeshi** [comment]
By the way, I remember this old issue you posted: https://github.com/BIDData/BIDMat/issues/31
Is this still an issue for you?

**Comment by danielchalef** [comment]
Thanks. I took a look at destress. Appears you're also using gensim. I'm looking for a means to convert the MAT output from BIDMach Word2Vec to Google C Word2Vec format. Am going to wade in deeper.

**Comment by danielchalef** [comment]
When I navigate to: https://gitter.im/BIDData/

I get the error below. Would you like me to speak to the Gitter team? I know one of the cofounders.

```

BIDData
You've tried to access BIDData's private organization room and you do not belong to this organization.

 Unfortunately this organization has no public rooms.
```

**Comment by DanielTakeshi** [comment]
Yeah, I tried to add you to the room, and it says you don't have permission. By hovering over the lock icon next to the name, it appears that only organization members (i.e., only those that have push access) can actually join.

Unfortunately, I'm not sure how to change these settings; there's a settings menu there but nothing seemed to work. Also, I don't even know if I *can* change these settings since John was the one who created it. @jcanny can you modify the gitter settings by, say, clicking on that lock icon next to the BID Data name, or that settings icon?

**Comment by DanielTakeshi** [comment]
Ah, I think I figured out the issue: https://gitter.zendesk.com/hc/en-us/articles/200178951-Gitter-rooms

Apparently, we need a BIDMach (not BID Data) gitter, because BID Data is the organization-level room.

**Comment by kovasb** [comment]
This would be very helpful.

**Comment by danielchalef** [comment]
Yeah I think there are two approaches: an org or team room (which is locked
down), or a public project room.

The latter is likely what we're looking for.

**Comment by jcanny** [comment]
OK, I added BIDMach and BIDMat. THey're supposed to be public. Do you 
see them now?

-John

**Comment by danielchalef** [comment]
I do. Brilliant. Thank you!
